### ISSUE TITLE
Device fails to log status when inactive

### ISSUE THREAD

**Issue by mansman12** [GloriousEggroll/AVMATRIX-VC12-4K-CAPTURE#6]
Thanks for making the driver, it works great when used however the issue I'm encountering is when there's no active signal in the device.

v4l2-input in OBS fails to log the status and spams the log file with:

`10:41:19.491: v4l2-input: /dev/video0: failed to log status`
`10:41:19.574: v4l2-input: /dev/video0: select timed out`

As soon as the capture card picks up a feed from an input, it's absolutely fine and logs properly:

`10:41:41.266: v4l2-input: Found device 'HUHDVideo 1' at /dev/video0`
`10:41:41.267: v4l2-input: Stepwise and Continuous framerates are currently hardcoded`
`10:41:41.267: v4l2-input: Stepwise and Continuous framerates are currently hardcoded`
`10:41:41.267: v4l2-input: Pixelformat: YUYV 4:2:2 (available)`
`10:41:41.267: v4l2-input: Pixelformat: RGB3 (Emulated) (unavailable)`
`10:41:41.267: v4l2-input: Pixelformat: BGR3 (Emulated) (available)`
`10:41:41.267: v4l2-input: Pixelformat: YU12 (Emulated) (available)`
`10:41:41.267: v4l2-input: Pixelformat: YV12 (Emulated) (available)`
`10:41:41.268: v4l2-input: Stepwise and Continuous framerates are currently hardcoded`
`10:41:41.268: v4l2-input: Found input 'HwsUHDX1Capture' (Index 0)`
`10:41:41.268: v4l2-input: Pixelformat: YUYV 4:2:2 (available)`
`10:41:41.268: v4l2-input: Pixelformat: RGB3 (Emulated) (unavailable)`
`10:41:41.268: v4l2-input: Pixelformat: BGR3 (Emulated) (available)`
`10:41:41.268: v4l2-input: Pixelformat: YU12 (Emulated) (available)`
`10:41:41.268: v4l2-input: Pixelformat: YV12 (Emulated) (available)`
`10:41:41.269: v4l2-input: Stepwise and Continuous framerates are currently hardcoded`
`10:41:45.840: v4l2-input: /dev/video0: Stopped capture after 1869 frames`
`10:41:45.842: v4l2-input: Start capture from /dev/video0`
`10:41:45.843: v4l2-input: Input: 0`
`10:41:45.843: v4l2-input: Resolution: 1920x1080`
`10:41:45.843: v4l2-input: Pixelformat: YUYV`
`10:41:45.843: v4l2-input: Linesize: 3840 Bytes`
`10:41:45.843: v4l2-input: Framerate: 60.00 fps`
`10:41:45.847: v4l2-input: /dev/video0: select timeout set to 83333 (5x frame periods)`

Capture cards I've used in the past tend to become inactive when there is no signal passed through them, is that not possible here or am I wrong about previous capture cards?

Also as a side question, is there any way to customise the images used for when there is no signal? I'd prefer having a black screen over a blue one but can understand if there's no scope for that.

Thanks!

**Comment by mansman12** [comment]
It looks like the issue might lie in `hws_video.c` for the following:

- `v4l2_model_get_support_framerate`
- `v4l2_get_suport_VideoFormatIndex`
- `v4l2_model_get_support_videoformat`
- `v4l2_model_get_support_pixformat`

They don't appear to use a fallback that v4l2 can understand when no inputs signal is detected, hence why v4l2 is unable to log status (I think).

The current fallback is either -1 or NULL which would have to be changed to something appropriate so v4l2 can tell there is no signal coming through.

**Comment by mansman12** [comment]
Temporary workaround is to set up a duplicate scene collection in OBS but remove the Video Capture Source for the capture card and switch back to this collection when a device is active.

**Comment by GloriousEggroll** [comment]
just a forewarning/note:

I did not make this driver. AVMatrix themselves made it based off a fork of magewell drivers. They don't maintain it (hasnt been updated since March 2023) and they host the files on a freaking windows drive. All I try to do here is keep it working as-is on updated kernels. I dont know what to do about the logging.

**Comment by mansman12** [comment]
Fair enough, would it be possible to keep the issue open in case someone who can fix it stumbles across it? Having it closed means there's zero chance anyone will see this.
