### ISSUE TITLE
DKMS build fails on kernel 6.8.1

### ISSUE THREAD

**Issue by aquova** [GloriousEggroll/AVMATRIX-VC12-4K-CAPTURE#7]
I've had this card for some time now using these drivers, and it's been working perfectly. Last night though, I updated my system to the latest kernel on Arch and noticed a dkms error for this card. Sure enough, when I went to use it today, it's no longer being recognized and attempting to uninstall and reinstall using the instructions yielded a build error (make log attached below).

I did try the Arch LTS kernel (currently 6.6.22), and that worked without any issues at all, so it seems to be some kernel-level change made in 6.8.

[make.log](https://github.com/GloriousEggroll/AVMATRIX-VC12-4K-CAPTURE/files/14643716/make.log)

**Comment by GloriousEggroll** [comment]
fixed by https://github.com/GloriousEggroll/AVMATRIX-VC12-4K-CAPTURE/pull/8/files
